services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: jdbc_schema
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d jdbc_schema" ]
      interval: 30s
      timeout: 10s
      retries: 5

  conductor:
    image: orkesio/orkes-conductor-community-standalone:latest
    init: true
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - redis:/redis
      - postgres:/pgdata

  cart:
    build: cart-service
    mem_limit: 512m
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

  purchase:
    build: purchase-service
    mem_limit: 512m
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

  warehouse:
    build: warehouse-service
    mem_limit: 512m
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:
  pgadmin-data:
  redis:
  postgres: