services:
  async-request-service:
    image: async-request-service
    build: async-request-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      lavinmq:
        condition: service_healthy

  async-response-service:
    image: async-response-service
    build: async-response-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      lavinmq:
        condition: service_healthy

#  rabbitmq:
#    image: rabbitmq:latest
#    mem_limit: 512m
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 5s
#      timeout: 2s
#      retries: 60

  lavinmq:
    image: cloudamqp/lavinmq:latest
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "lavinmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60
