server:
    port: 8081

    spring:
        application:
            name: date-service

    cloud:
        zookeeper:
            connect-string: localhost:2181
            discovery:
                enabled: true
                root: /services
            config:
                enabled: true
                root: /config

    config:
        import: "optional:zookeeper:"